```yaml
trigger:
  branches:
    include: [ main ]

pool:
  vmImage: 'windows-latest' # یا ubuntu-latest

variables:
  BuildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: 'src/**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'src/**/*.csproj'
    arguments: '-c $(BuildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: 'tests/**/*.csproj'
    arguments: '--no-build --verbosity normal'
    publishTestResults: true
