# azure-pipelines.yml - clean ASCII, no tabs
trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: windows-latest

variables:
  BuildConfiguration: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

steps:
  - task: UseDotNet@2
    displayName: Use .NET SDK 8.x
    inputs:
      packageType: sdk
      version: 8.0.x
      performMultiLevelLookup: true

  - task: Cache@2
    displayName: Cache NuGet
    inputs:
      key: 'nuget | $(Agent.OS) | **/packages.lock.json, **/*.csproj'
      restoreKeys: |
        nuget | $(Agent.OS)
      path: $(NUGET_PACKAGES)

  - script: dotnet restore
    displayName: Restore

  - script: dotnet build --configuration $(BuildConfiguration) --no-restore
    displayName: Build

  - script: dotnet test --configuration $(BuildConfiguration) --no-build --verbosity normal
    displayName: Test
    continueOnError: true

  # To publish a web project, uncomment and set the correct .csproj path:
  # - script: dotnet publish path/to/YourWebProject.csproj -c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)/publish
  #   displayName: Publish Web App

  # - task: PublishBuildArtifacts@1
  #   inputs:
  #     PathtoPublish: $(Build.ArtifactStagingDirectory)/publish
  #     ArtifactName: drop
  #     publishLocation: Container
